apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-beta
spec:
  storageClassName: database
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/beta"